title: Carter’s Portfolio
description: 'My amazing portfolio '
social_link: RocketNinja15
social_username: RocketNinja15
github_repo: RocketNinja15
github_username: RocketNinja15
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /good
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
